[package]
name = "pomodoro"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.1"
gtk = { version = "0.9.4", package = "gtk4", features = ["v4_16"] }
tokio = { version = "1.42.0", features = ["full"]}

[build-dependencies]
glib-build-tools = "0.20.0"
